title: Introduction to Digital Humanities
description: HIST 105B, Alice McGrath, Spring 2025 at Bryn Mawr College

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

collections:
  wk:
    output: true